apiVersion: v1
kind: Service
metadata:
  name: {{ template "kube-eagle.fullname" . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "labels.selector" . | nindent 4 }}